### ISSUE TITLE
missing Lua.call4 ... Lua.callN ... Lua.method4 ... Lua.methodN

### ISSUE THREAD

**Issue by mnegovanovic** [minoki/LunarML#17]
Hi

I am working on openresty LunarML integration. There are Lua instance methods that return (a,b,c,d) 4 item "tuples". I am in a need of Lua.method4.

Regards

**Comment by minoki** [comment]
OK, I'll add more `Lua.methodN` in the future.

For now, you can use `Lua.method` to capture results from a Lua method. It is equivalent to `table.pack(obj:method(...))`. The SML code would look like:

```sml
val results = Lua.method (obj, "method") #[arg0, arg1]
val a = Vector.sub (results, 0)
val b = Vector.sub (results, 1)
val c = Vector.sub (results, 2)
val d = Vector.sub (results, 3)
```

**Comment by mnegovanovic** [comment]
understood ... cheers.

Regards
