### ISSUE TITLE
What should be the $(SML_LIB) behavior?

### ISSUE THREAD

**Issue by ratsclub** [minoki/LunarML#8]
I have a small `.mlb` file containing the following:

```mlb
$(SML_LIB)/basis/basis.mlb
src/main.sml
```

Compiling with MLton and MLKit works just fine. However, with LunarML I get this error:

```sh
$ lunarml compile sources.mlb 
io error: $PROJECT/../lib/lunarml/ml/basis/basis.mlb, openIn, SysErr
```

Is there something I need to do?

**Comment by minoki** [comment]
Did you move `lunarml` executable from `<LunarML repo>/bin`? If so, try setting `-B` option like this:

```
$ lunarml -B<LunarML repo>/lib/lunarml compile sources.mlb
```

Creating a proper installer (`make install`) is on my to-do list.

**Comment by ratsclub** [comment]
Oh, this did fix the problem. I'm able to compile, right now! 

Just for some context, I'm trying to target lunarml on [my project's](https://github.com/PerplexSystems/Railroad) CI. I'm also using the Nix package for `lunarml`:

```nix
"${pkgs.lunarml}/bin/lunarml compile -B ${pkgs.lunarml}/lib/lunarml sources.mlb"
```

However, running the code now yields another problem, but I guess this should be another issue.

```sh
lua: tests.lua:113: unexpected symbol near '/'
```

Thank you so much!
